Mo: mo::models::Document Class Reference
mo::models::Document Class Reference
#include <Document.hpp>
Signals
void filePathChanged (const QString &path)
void contentChanged (const QString &content)
void modifiedChanged (bool modified)
void encodingChanged (const QString &encoding)
void languageChanged (const QString &language)
Public Member Functions
Document (QObject *parent=nullptr)
QString filePath () const
QString content () const
bool isModified () const
QString encoding () const
QString language () const
void setContent (const QString &content)
void setEncoding (const QString &encoding)
void setLanguage (const QString &language)
bool load (const QString &path)
bool save ()
bool saveAs (const QString &path)
Properties
QString filePath
QString content
bool isModified
QString encoding
QString language
Private Member Functions
void setModified (bool modified)
void setFilePath (const QString &path)
Private Attributes
QString filePath_
QString content_
bool modified_ = false
QString encoding_ = QStringLiteral("UTF-8")
QString language_ = QStringLiteral("Plain Text")
Detailed Description
Definition at line 11 of file Document.hpp.
Constructor & Destructor Documentation
Document()
mo::models::Document::Document (QObject * parent = nullptr) explicit
Definition at line 13 of file Document.cpp.
Member Function Documentation
content()
QString mo::models::Document::content () const
Definition at line 16 of file Document.cpp.
References content_.
contentChanged
void mo::models::Document::contentChanged (const QString & content) signal
References content, and contentChanged().
Referenced by contentChanged(), load(), and setContent().
encoding()
QString mo::models::Document::encoding () const
Definition at line 18 of file Document.cpp.
References encoding_.
encodingChanged
void mo::models::Document::encodingChanged (const QString & encoding) signal
References encoding, and encodingChanged().
Referenced by encodingChanged(), and setEncoding().
filePath()
QString mo::models::Document::filePath () const
Definition at line 15 of file Document.cpp.
References filePath_.
filePathChanged
void mo::models::Document::filePathChanged (const QString & path) signal
References filePathChanged().
Referenced by filePathChanged(), and setFilePath().
isModified()
bool mo::models::Document::isModified () const
Definition at line 17 of file Document.cpp.
References modified_.
language()
QString mo::models::Document::language () const
Definition at line 19 of file Document.cpp.
References language_.
languageChanged
void mo::models::Document::languageChanged (const QString & language) signal
References language, languageChanged(), setFilePath(), and setModified().
Referenced by languageChanged(), and setLanguage().
load()
bool mo::models::Document::load (const QString & path)
Definition at line 46 of file Document.cpp.
References content_, contentChanged(), setFilePath(), and setModified().
modifiedChanged
void mo::models::Document::modifiedChanged (bool modified) signal
References modifiedChanged().
Referenced by modifiedChanged(), and setModified().
save()
bool mo::models::Document::save ()
Definition at line 63 of file Document.cpp.
References filePath_, and saveAs().
saveAs()
bool mo::models::Document::saveAs (const QString & path)
Definition at line 71 of file Document.cpp.
References content_, setFilePath(), and setModified().
Referenced by save().
setContent()
void mo::models::Document::setContent (const QString & content)
Definition at line 21 of file Document.cpp.
References content, content_, contentChanged(), and setModified().
setEncoding()
void mo::models::Document::setEncoding (const QString & encoding)
Definition at line 30 of file Document.cpp.
References encoding, encoding_, and encodingChanged().
setFilePath()
void mo::models::Document::setFilePath (const QString & path) private
Definition at line 95 of file Document.cpp.
References filePath_, and filePathChanged().
Referenced by languageChanged(), load(), and saveAs().
setLanguage()
void mo::models::Document::setLanguage (const QString & language)
Definition at line 38 of file Document.cpp.
References language, language_, and languageChanged().
setModified()
void mo::models::Document::setModified (bool modified) private
Definition at line 87 of file Document.cpp.
References modified_, and modifiedChanged().
Referenced by languageChanged(), load(), saveAs(), and setContent().
Member Data Documentation
content_
QString mo::models::Document::content_ private
Definition at line 49 of file Document.hpp.
Referenced by content(), load(), saveAs(), and setContent().
encoding_
QString mo::models::Document::encoding_ = QStringLiteral("UTF-8") private
Definition at line 51 of file Document.hpp.
Referenced by encoding(), and setEncoding().
filePath_
QString mo::models::Document::filePath_ private
Definition at line 48 of file Document.hpp.
Referenced by filePath(), save(), and setFilePath().
language_
QString mo::models::Document::language_ = QStringLiteral("Plain Text") private
Definition at line 52 of file Document.hpp.
Referenced by language(), and setLanguage().
modified_
bool mo::models::Document::modified_ = false private
Definition at line 50 of file Document.hpp.
Referenced by isModified(), and setModified().
Property Documentation
content
QString mo::models::Document::content read write
Definition at line 15 of file Document.hpp.
Referenced by contentChanged(), and setContent().
encoding
QString mo::models::Document::encoding read
Definition at line 17 of file Document.hpp.
Referenced by encodingChanged(), and setEncoding().
filePath
QString mo::models::Document::filePath read
Definition at line 14 of file Document.hpp.
isModified
bool mo::models::Document::isModified read
Definition at line 16 of file Document.hpp.
language
QString mo::models::Document::language read
Definition at line 18 of file Document.hpp.
Referenced by languageChanged(), and setLanguage().
The documentation for this class was generated from the following files:
src/models/include/mo/models/Document.hpp
src/models/src/Document.cpp