Mo: mo::ui::MainWindow Class Reference
mo::ui::MainWindow Class Reference
#include <MainWindow.hpp>
Public Slots
void fileNew ()
void fileOpen ()
void fileSave ()
void fileSaveAs ()
void fileSaveAll ()
void fileCloseTab ()
void fileQuit ()
void editUndo ()
void editRedo ()
void editCut ()
void editCopy ()
void editPaste ()
void editSelectAll ()
void editFind ()
void editFindNext ()
void editFindPrev ()
void editPreferences ()
void viewToggleLineNumbers (bool on)
void viewToggleToolBar (bool on)
void viewZoomIn ()
void viewZoomOut ()
void viewZoomReset ()
void helpAbout ()
Public Member Functions
MainWindow (QWidget *parent=nullptr)
~MainWindow () override
void openFile (const QString &path)
void newTab ()
void closeTab (int index)
void saveSession ()
Protected Member Functions
void closeEvent (QCloseEvent *event) override
Private Slots
void onTabChanged (int index)
void onTabCloseRequested (int index)
void onFileChanged (const QString &path)
void onSettingsChanged ()
void onEditorTitleChanged (const QString &title)
void onEditorModificationChanged (bool modified)
Private Member Functions
void buildMenus ()
void buildToolBar ()
void applyTheme ()
void applyIconTheme ()
void applyEditorSettingsToAll ()
void updateRecentFilesMenu ()
void loadStyleSheet (const QString &name)
void updateTabTitle (int index)
CodeEditor * currentEditor () const
Private Attributes
QTabWidget * tabWidget_ = nullptr
QToolBar * toolBar_ = nullptr
QMenu * recentFilesMenu_ = nullptr
QAction * toggleLineNumbersAction_ = nullptr
QAction * toggleToolBarAction_ = nullptr
FindReplaceDock * findDock_ = nullptr
QFileSystemWatcher * fileWatcher_ = nullptr
QStringList recentFiles_
Detailed Description
Definition at line 21 of file MainWindow.hpp.
Constructor & Destructor Documentation
MainWindow()
mo::ui::MainWindow::MainWindow (QWidget * parent = nullptr) explicit
Definition at line 32 of file MainWindow.cpp.
References applyIconTheme(), applyTheme(), buildMenus(), buildToolBar(), fileWatcher_, findDock_, mo::core::Settings::instance(), mo::core::constants::kApplicationName, mo::services::SessionManager::loadSession(), newTab(), onFileChanged(), onTabChanged(), onTabCloseRequested(), openFile(), mo::core::Settings::recentFiles, recentFiles_, tabWidget_, mo::core::Settings::themeChanged(), and updateRecentFilesMenu().
~MainWindow()
mo::ui::MainWindow::~MainWindow () override default
Member Function Documentation
applyEditorSettingsToAll()
void mo::ui::MainWindow::applyEditorSettingsToAll () private
Definition at line 242 of file MainWindow.cpp.
References mo::core::Settings::instance(), tabWidget_, and toggleLineNumbersAction_.
Referenced by onSettingsChanged().
applyIconTheme()
void mo::ui::MainWindow::applyIconTheme () private
Definition at line 224 of file MainWindow.cpp.
References mo::core::Settings::iconTheme, and mo::core::Settings::instance().
Referenced by MainWindow(), and onSettingsChanged().
applyTheme()
void mo::ui::MainWindow::applyTheme () private
Definition at line 205 of file MainWindow.cpp.
References mo::core::Settings::instance(), loadStyleSheet(), tabWidget_, and mo::core::Settings::theme.
Referenced by MainWindow(), and onSettingsChanged().
buildMenus()
void mo::ui::MainWindow::buildMenus () private
Definition at line 94 of file MainWindow.cpp.
References editCopy(), editCut(), editFind(), editFindNext(), editFindPrev(), editPaste(), editPreferences(), editRedo(), editSelectAll(), editUndo(), fileCloseTab(), fileNew(), fileOpen(), fileQuit(), fileSave(), fileSaveAll(), fileSaveAs(), helpAbout(), mo::core::Settings::instance(), recentFilesMenu_, toggleLineNumbersAction_, toggleToolBarAction_, viewToggleLineNumbers(), viewToggleToolBar(), viewZoomIn(), viewZoomOut(), and viewZoomReset().
Referenced by MainWindow().
buildToolBar()
void mo::ui::MainWindow::buildToolBar () private
Definition at line 178 of file MainWindow.cpp.
References editCopy(), editCut(), editFind(), editPaste(), editRedo(), editUndo(), fileNew(), fileOpen(), fileSave(), fileSaveAll(), fileSaveAs(), and toolBar_.
Referenced by MainWindow().
closeEvent()
void mo::ui::MainWindow::closeEvent (QCloseEvent * event) override protected
Definition at line 601 of file MainWindow.cpp.
References saveSession(), and tabWidget_.
closeTab()
void mo::ui::MainWindow::closeTab (int index)
Definition at line 339 of file MainWindow.cpp.
References newTab(), and tabWidget_.
Referenced by fileCloseTab(), onFileChanged(), and onTabCloseRequested().
currentEditor()
CodeEditor * mo::ui::MainWindow::currentEditor () const private
Definition at line 89 of file MainWindow.cpp.
References tabWidget_.
Referenced by editCopy(), editCut(), editFindNext(), editFindPrev(), editPaste(), editRedo(), editSelectAll(), editUndo(), fileSave(), fileSaveAs(), viewZoomIn(), viewZoomOut(), and viewZoomReset().
editCopy
void mo::ui::MainWindow::editCopy () slot
Definition at line 509 of file MainWindow.cpp.
References currentEditor().
Referenced by buildMenus(), and buildToolBar().
editCut
void mo::ui::MainWindow::editCut () slot
Definition at line 504 of file MainWindow.cpp.
References currentEditor().
Referenced by buildMenus(), and buildToolBar().
editFind
void mo::ui::MainWindow::editFind () slot
Definition at line 524 of file MainWindow.cpp.
References findDock_.
Referenced by buildMenus(), and buildToolBar().
editFindNext
void mo::ui::MainWindow::editFindNext () slot
Definition at line 531 of file MainWindow.cpp.
References currentEditor(), and findDock_.
Referenced by buildMenus().
editFindPrev
void mo::ui::MainWindow::editFindPrev () slot
Definition at line 536 of file MainWindow.cpp.
References currentEditor(), and findDock_.
Referenced by buildMenus().
editPaste
void mo::ui::MainWindow::editPaste () slot
Definition at line 514 of file MainWindow.cpp.
References currentEditor().
Referenced by buildMenus(), and buildToolBar().
editPreferences
void mo::ui::MainWindow::editPreferences () slot
Definition at line 541 of file MainWindow.cpp.
References onSettingsChanged(), and mo::ui::SettingsDialog::settingsChanged().
Referenced by buildMenus().
editRedo
void mo::ui::MainWindow::editRedo () slot
Definition at line 499 of file MainWindow.cpp.
References currentEditor().
Referenced by buildMenus(), and buildToolBar().
editSelectAll
void mo::ui::MainWindow::editSelectAll () slot
Definition at line 519 of file MainWindow.cpp.
References currentEditor().
Referenced by buildMenus().
editUndo
void mo::ui::MainWindow::editUndo () slot
Definition at line 494 of file MainWindow.cpp.
References currentEditor().
Referenced by buildMenus(), and buildToolBar().
fileCloseTab
void mo::ui::MainWindow::fileCloseTab () slot
Definition at line 485 of file MainWindow.cpp.
References closeTab(), and tabWidget_.
Referenced by buildMenus().
fileNew
void mo::ui::MainWindow::fileNew () slot
Definition at line 436 of file MainWindow.cpp.
References newTab().
Referenced by buildMenus(), and buildToolBar().
fileOpen
void mo::ui::MainWindow::fileOpen () slot
Definition at line 438 of file MainWindow.cpp.
References openFile().
Referenced by buildMenus(), and buildToolBar().
fileQuit
void mo::ui::MainWindow::fileQuit () slot
Definition at line 490 of file MainWindow.cpp.
Referenced by buildMenus().
fileSave
void mo::ui::MainWindow::fileSave () slot
Definition at line 446 of file MainWindow.cpp.
References currentEditor().
Referenced by buildMenus(), and buildToolBar().
fileSaveAll
void mo::ui::MainWindow::fileSaveAll () slot
Definition at line 469 of file MainWindow.cpp.
References fileSaveAs(), and tabWidget_.
Referenced by buildMenus(), and buildToolBar().
fileSaveAs
void mo::ui::MainWindow::fileSaveAs () slot
Definition at line 454 of file MainWindow.cpp.
References currentEditor(), and tabWidget_.
Referenced by buildMenus(), buildToolBar(), and fileSaveAll().
helpAbout
void mo::ui::MainWindow::helpAbout () slot
Definition at line 592 of file MainWindow.cpp.
References mo::core::constants::kApplicationVersion.
Referenced by buildMenus().
loadStyleSheet()
void mo::ui::MainWindow::loadStyleSheet (const QString & name) private
Definition at line 255 of file MainWindow.cpp.
Referenced by applyTheme().
newTab()
void mo::ui::MainWindow::newTab ()
Definition at line 293 of file MainWindow.cpp.
References mo::ui::CodeEditor::modificationChanged(), onEditorModificationChanged(), onEditorTitleChanged(), tabWidget_, and mo::ui::CodeEditor::titleChanged().
Referenced by closeTab(), fileNew(), and MainWindow().
onEditorModificationChanged
void mo::ui::MainWindow::onEditorModificationChanged (bool modified) private slot
Definition at line 423 of file MainWindow.cpp.
References tabWidget_.
Referenced by newTab(), and openFile().
onEditorTitleChanged
void mo::ui::MainWindow::onEditorTitleChanged (const QString & title) private slot
Definition at line 413 of file MainWindow.cpp.
References tabWidget_.
Referenced by newTab(), and openFile().
onFileChanged
void mo::ui::MainWindow::onFileChanged (const QString & path) private slot
Definition at line 377 of file MainWindow.cpp.
References closeTab(), mo::core::Logger::info(), and tabWidget_.
Referenced by MainWindow().
onSettingsChanged
void mo::ui::MainWindow::onSettingsChanged () private slot
Definition at line 406 of file MainWindow.cpp.
References applyEditorSettingsToAll(), applyIconTheme(), and applyTheme().
Referenced by editPreferences().
onTabChanged
void mo::ui::MainWindow::onTabChanged (int index) private slot
Definition at line 373 of file MainWindow.cpp.
Referenced by MainWindow().
onTabCloseRequested
void mo::ui::MainWindow::onTabCloseRequested (int index) private slot
Definition at line 375 of file MainWindow.cpp.
References closeTab().
Referenced by MainWindow().
openFile()
void mo::ui::MainWindow::openFile (const QString & path)
Definition at line 302 of file MainWindow.cpp.
References fileWatcher_, mo::core::Settings::instance(), mo::ui::CodeEditor::modificationChanged(), onEditorModificationChanged(), onEditorTitleChanged(), recentFiles_, mo::core::Settings::setRecentFiles(), tabWidget_, mo::ui::CodeEditor::titleChanged(), and updateRecentFilesMenu().
Referenced by fileOpen(), MainWindow(), and updateRecentFilesMenu().
saveSession()
void mo::ui::MainWindow::saveSession ()
Definition at line 622 of file MainWindow.cpp.
References mo::services::SessionState::openFiles, mo::services::SessionManager::saveSession(), tabWidget_, mo::services::SessionState::windowGeometry, and mo::services::SessionState::windowState.
Referenced by closeEvent().
updateRecentFilesMenu()
void mo::ui::MainWindow::updateRecentFilesMenu () private
Definition at line 267 of file MainWindow.cpp.
References mo::core::Settings::instance(), openFile(), recentFiles_, recentFilesMenu_, mo::core::Settings::setRecentFiles(), and updateRecentFilesMenu().
Referenced by MainWindow(), openFile(), and updateRecentFilesMenu().
updateTabTitle()
void mo::ui::MainWindow::updateTabTitle (int index) private
Definition at line 362 of file MainWindow.cpp.
References tabWidget_.
viewToggleLineNumbers
void mo::ui::MainWindow::viewToggleLineNumbers (bool on) slot
Definition at line 550 of file MainWindow.cpp.
References mo::core::Settings::instance(), mo::core::Settings::save(), mo::core::Settings::setShowLineNumbers(), and tabWidget_.
Referenced by buildMenus().
viewToggleToolBar
void mo::ui::MainWindow::viewToggleToolBar (bool on) slot
Definition at line 562 of file MainWindow.cpp.
References toolBar_.
Referenced by buildMenus().
viewZoomIn
void mo::ui::MainWindow::viewZoomIn () slot
Definition at line 569 of file MainWindow.cpp.
References currentEditor().
Referenced by buildMenus().
viewZoomOut
void mo::ui::MainWindow::viewZoomOut () slot
Definition at line 574 of file MainWindow.cpp.
References currentEditor().
Referenced by buildMenus().
viewZoomReset
void mo::ui::MainWindow::viewZoomReset () slot
Definition at line 579 of file MainWindow.cpp.
References currentEditor(), and mo::core::Settings::instance().
Referenced by buildMenus().
Member Data Documentation
fileWatcher_
QFileSystemWatcher* mo::ui::MainWindow::fileWatcher_ = nullptr private
Definition at line 91 of file MainWindow.hpp.
Referenced by MainWindow(), and openFile().
findDock_
FindReplaceDock* mo::ui::MainWindow::findDock_ = nullptr private
Definition at line 90 of file MainWindow.hpp.
Referenced by editFind(), editFindNext(), editFindPrev(), and MainWindow().
recentFiles_
QStringList mo::ui::MainWindow::recentFiles_ private
Definition at line 92 of file MainWindow.hpp.
Referenced by MainWindow(), openFile(), and updateRecentFilesMenu().
recentFilesMenu_
QMenu* mo::ui::MainWindow::recentFilesMenu_ = nullptr private
Definition at line 87 of file MainWindow.hpp.
Referenced by buildMenus(), and updateRecentFilesMenu().
tabWidget_
QTabWidget* mo::ui::MainWindow::tabWidget_ = nullptr private
Definition at line 85 of file MainWindow.hpp.
Referenced by applyEditorSettingsToAll(), applyTheme(), closeEvent(), closeTab(), currentEditor(), fileCloseTab(), fileSaveAll(), fileSaveAs(), MainWindow(), newTab(), onEditorModificationChanged(), onEditorTitleChanged(), onFileChanged(), openFile(), saveSession(), updateTabTitle(), and viewToggleLineNumbers().
toggleLineNumbersAction_
QAction* mo::ui::MainWindow::toggleLineNumbersAction_ = nullptr private
Definition at line 88 of file MainWindow.hpp.
Referenced by applyEditorSettingsToAll(), and buildMenus().
toggleToolBarAction_
QAction* mo::ui::MainWindow::toggleToolBarAction_ = nullptr private
Definition at line 89 of file MainWindow.hpp.
Referenced by buildMenus().
toolBar_
QToolBar* mo::ui::MainWindow::toolBar_ = nullptr private
Definition at line 86 of file MainWindow.hpp.
Referenced by buildToolBar(), and viewToggleToolBar().
The documentation for this class was generated from the following files:
src/ui/mainwindow/MainWindow.hpp
src/ui/mainwindow/MainWindow.cpp