Mo: mo::app::Application Class Reference
mo::app::Application Class Reference
#include <Application.hpp>
Public Member Functions
Application (int &argc, char **argv)
~Application () override
int run ()
Private Slots
void saveSession ()
Private Member Functions
void loadTranslation ()
void initLogging ()
Private Attributes
std::unique_ptr< SingleInstance > singleInstance_
std::unique_ptr< mo::ui::MainWindow > mainWindow_
Detailed Description
Definition at line 17 of file Application.hpp.
Constructor & Destructor Documentation
Application()
mo::app::Application::Application (int & argc, char ** argv) explicit
Definition at line 19 of file Application.cpp.
References initLogging(), mo::core::Settings::instance(), mo::core::constants::kApplicationId, mo::core::constants::kApplicationName, mo::core::constants::kApplicationVersion, mo::core::constants::kOrganizationName, mo::core::Settings::load(), loadTranslation(), mainWindow_, singleInstance_, and mo::core::Logger::warning().
~Application()
mo::app::Application::~Application () override default
Member Function Documentation
initLogging()
void mo::app::Application::initLogging () private
Definition at line 84 of file Application.cpp.
References mo::core::Logger::init().
Referenced by Application().
loadTranslation()
void mo::app::Application::loadTranslation () private
Definition at line 63 of file Application.cpp.
References mo::core::Logger::warning().
Referenced by Application().
run()
int mo::app::Application::run ()
Definition at line 45 of file Application.cpp.
References mainWindow_, and saveSession().
Referenced by main().
saveSession
void mo::app::Application::saveSession () private slot
Definition at line 55 of file Application.cpp.
References mo::core::Settings::instance(), mainWindow_, and mo::core::Settings::save().
Referenced by run().
Member Data Documentation
mainWindow_
std::unique_ptr<mo::ui::MainWindow> mo::app::Application::mainWindow_ private
Definition at line 35 of file Application.hpp.
Referenced by Application(), run(), and saveSession().
singleInstance_
std::unique_ptr<SingleInstance> mo::app::Application::singleInstance_ private
Definition at line 34 of file Application.hpp.
Referenced by Application().
The documentation for this class was generated from the following files:
src/app/Application.hpp
src/app/Application.cpp