Mo: mo::core::Settings Class Reference
mo::core::Settings Class Reference
#include <Settings.hpp>
Public Types
enum class Theme { System , Light , Dark }
Signals
void fontFamilyChanged (const QString &font)
void fontSizeChanged (int size)
void themeChanged (const QString &theme)
void iconThemeChanged (const QString &iconTheme)
void tabWidthChanged (int width)
void showLineNumbersChanged (bool show)
void autoIndentChanged (bool enabled)
void recentFilesChanged (const QStringList &files)
Public Member Functions
void load ()
void save ()
QString fontFamily () const
void setFontFamily (const QString &font)
int fontSize () const
void setFontSize (int size)
QString theme () const
void setTheme (const QString &theme)
QString iconTheme () const
void setIconTheme (const QString &iconTheme)
int tabWidth () const
void setTabWidth (int width)
bool showLineNumbers () const
void setShowLineNumbers (bool show)
bool autoIndent () const
void setAutoIndent (bool enabled)
QStringList recentFiles () const
void setRecentFiles (const QStringList &files)
void addRecentFile (const QString &path)
Static Public Member Functions
static Settings & instance ()
Properties
QString fontFamily
int fontSize
QString theme
QString iconTheme
int tabWidth
bool showLineNumbers
bool autoIndent
QStringList recentFiles
Private Member Functions
Settings ()
~Settings () override
Settings (const Settings &)=delete
Settings & operator= (const Settings &)=delete
Private Attributes
std::unique_ptr< QSettings > settings_
QString fontFamily_ = QStringLiteral("Monospace")
int fontSize_ = 11
QString theme_ = QStringLiteral("System")
QString iconTheme_ = QStringLiteral("Breeze")
int tabWidth_ = 4
bool showLineNumbers_ = true
bool autoIndent_ = true
QStringList recentFiles_
Detailed Description
Definition at line 15 of file Settings.hpp.
Member Enumeration Documentation
Theme
enum class mo::core::Settings::Theme strong
Enumerator
System
Light
Dark
Definition at line 28 of file Settings.hpp.
Constructor & Destructor Documentation
Settings() [1/2]
mo::core::Settings::Settings () private
Definition at line 19 of file Settings.cpp.
References mo::core::constants::kSettingsFile, and settings_.
Referenced by instance(), operator=(), and Settings().
~Settings()
mo::core::Settings::~Settings () override private default
Settings() [2/2]
mo::core::Settings::Settings (const Settings &) private delete
References Settings().
Member Function Documentation
addRecentFile()
void mo::core::Settings::addRecentFile (const QString & path)
Definition at line 136 of file Settings.cpp.
References recentFiles_, and recentFilesChanged().
autoIndent()
bool mo::core::Settings::autoIndent () const
Definition at line 116 of file Settings.cpp.
References autoIndent_.
autoIndentChanged
void mo::core::Settings::autoIndentChanged (bool enabled) signal
Referenced by setAutoIndent().
fontFamily()
QString mo::core::Settings::fontFamily () const
Definition at line 56 of file Settings.cpp.
References fontFamily_.
fontFamilyChanged
void mo::core::Settings::fontFamilyChanged (const QString & font) signal
Referenced by setFontFamily().
fontSize()
int mo::core::Settings::fontSize () const
Definition at line 66 of file Settings.cpp.
References fontSize_.
fontSizeChanged
void mo::core::Settings::fontSizeChanged (int size) signal
Referenced by setFontSize().
iconTheme()
QString mo::core::Settings::iconTheme () const
Definition at line 86 of file Settings.cpp.
References iconTheme_.
iconThemeChanged
void mo::core::Settings::iconThemeChanged (const QString & iconTheme) signal
References iconTheme.
Referenced by setIconTheme().
instance()
Settings & mo::core::Settings::instance () static
Definition at line 13 of file Settings.cpp.
References Settings().
Referenced by mo::app::Application::Application(), mo::ui::CodeEditor::applyEditorSettings(), mo::ui::MainWindow::applyEditorSettingsToAll(), mo::ui::MainWindow::applyIconTheme(), mo::ui::MainWindow::applyTheme(), mo::ui::MainWindow::buildMenus(), mo::ui::CodeEditor::keyPressEvent(), mo::ui::SettingsDialog::load(), mo::ui::MainWindow::MainWindow(), mo::ui::MainWindow::openFile(), mo::ui::SettingsDialog::save(), mo::app::Application::saveSession(), mo::ui::MainWindow::updateRecentFilesMenu(), mo::ui::MainWindow::viewToggleLineNumbers(), and mo::ui::MainWindow::viewZoomReset().
load()
void mo::core::Settings::load ()
Definition at line 30 of file Settings.cpp.
References autoIndent_, fontFamily_, fontSize_, iconTheme_, recentFiles_, setAutoIndent(), setFontFamily(), setFontSize(), setIconTheme(), setRecentFiles(), setShowLineNumbers(), setTabWidth(), setTheme(), settings_, showLineNumbers_, tabWidth_, and theme_.
Referenced by mo::app::Application::Application().
operator=()
Settings & mo::core::Settings::operator= (const Settings &) private delete
References Settings().
recentFiles()
QStringList mo::core::Settings::recentFiles () const
Definition at line 126 of file Settings.cpp.
References recentFiles_.
recentFilesChanged
void mo::core::Settings::recentFilesChanged (const QStringList & files) signal
Referenced by addRecentFile(), and setRecentFiles().
save()
void mo::core::Settings::save ()
Definition at line 43 of file Settings.cpp.
References autoIndent_, fontFamily_, fontSize_, iconTheme_, recentFiles_, settings_, showLineNumbers_, tabWidth_, and theme_.
Referenced by mo::app::Application::saveSession(), and mo::ui::MainWindow::viewToggleLineNumbers().
setAutoIndent()
void mo::core::Settings::setAutoIndent (bool enabled)
Definition at line 118 of file Settings.cpp.
References autoIndent_, and autoIndentChanged().
Referenced by load().
setFontFamily()
void mo::core::Settings::setFontFamily (const QString & font)
Definition at line 58 of file Settings.cpp.
References fontFamily_, and fontFamilyChanged().
Referenced by load().
setFontSize()
void mo::core::Settings::setFontSize (int size)
Definition at line 68 of file Settings.cpp.
References fontSize_, and fontSizeChanged().
Referenced by load().
setIconTheme()
void mo::core::Settings::setIconTheme (const QString & iconTheme)
Definition at line 88 of file Settings.cpp.
References iconTheme, iconTheme_, and iconThemeChanged().
Referenced by load().
setRecentFiles()
void mo::core::Settings::setRecentFiles (const QStringList & files)
Definition at line 128 of file Settings.cpp.
References recentFiles_, and recentFilesChanged().
Referenced by load(), mo::ui::MainWindow::openFile(), and mo::ui::MainWindow::updateRecentFilesMenu().
setShowLineNumbers()
void mo::core::Settings::setShowLineNumbers (bool show)
Definition at line 108 of file Settings.cpp.
References showLineNumbers_, and showLineNumbersChanged().
Referenced by load(), and mo::ui::MainWindow::viewToggleLineNumbers().
setTabWidth()
void mo::core::Settings::setTabWidth (int width)
Definition at line 98 of file Settings.cpp.
References tabWidth_, and tabWidthChanged().
Referenced by load().
setTheme()
void mo::core::Settings::setTheme (const QString & theme)
Definition at line 78 of file Settings.cpp.
References theme, theme_, and themeChanged().
Referenced by load().
showLineNumbers()
bool mo::core::Settings::showLineNumbers () const
Definition at line 106 of file Settings.cpp.
References showLineNumbers_.
showLineNumbersChanged
void mo::core::Settings::showLineNumbersChanged (bool show) signal
Referenced by setShowLineNumbers().
tabWidth()
int mo::core::Settings::tabWidth () const
Definition at line 96 of file Settings.cpp.
References tabWidth_.
tabWidthChanged
void mo::core::Settings::tabWidthChanged (int width) signal
Referenced by setTabWidth().
theme()
QString mo::core::Settings::theme () const
Definition at line 76 of file Settings.cpp.
References theme_.
themeChanged
void mo::core::Settings::themeChanged (const QString & theme) signal
References theme.
Referenced by mo::ui::MainWindow::MainWindow(), and setTheme().
Member Data Documentation
autoIndent_
bool mo::core::Settings::autoIndent_ = true private
Definition at line 86 of file Settings.hpp.
Referenced by autoIndent(), load(), save(), and setAutoIndent().
fontFamily_
QString mo::core::Settings::fontFamily_ = QStringLiteral("Monospace") private
Definition at line 80 of file Settings.hpp.
Referenced by fontFamily(), load(), save(), and setFontFamily().
fontSize_
int mo::core::Settings::fontSize_ = 11 private
Definition at line 81 of file Settings.hpp.
Referenced by fontSize(), load(), save(), and setFontSize().
iconTheme_
QString mo::core::Settings::iconTheme_ = QStringLiteral("Breeze") private
Definition at line 83 of file Settings.hpp.
Referenced by iconTheme(), load(), save(), and setIconTheme().
recentFiles_
QStringList mo::core::Settings::recentFiles_ private
Definition at line 87 of file Settings.hpp.
Referenced by addRecentFile(), load(), recentFiles(), save(), and setRecentFiles().
settings_
std::unique_ptr<QSettings> mo::core::Settings::settings_ private
Definition at line 78 of file Settings.hpp.
Referenced by load(), save(), and Settings().
showLineNumbers_
bool mo::core::Settings::showLineNumbers_ = true private
Definition at line 85 of file Settings.hpp.
Referenced by load(), save(), setShowLineNumbers(), and showLineNumbers().
tabWidth_
int mo::core::Settings::tabWidth_ = 4 private
Definition at line 84 of file Settings.hpp.
Referenced by load(), save(), setTabWidth(), and tabWidth().
theme_
QString mo::core::Settings::theme_ = QStringLiteral("System") private
Definition at line 82 of file Settings.hpp.
Referenced by load(), save(), setTheme(), and theme().
Property Documentation
autoIndent
bool mo::core::Settings::autoIndent read write
Definition at line 24 of file Settings.hpp.
fontFamily
QString mo::core::Settings::fontFamily read write
Definition at line 18 of file Settings.hpp.
fontSize
int mo::core::Settings::fontSize read write
Definition at line 19 of file Settings.hpp.
iconTheme
QString mo::core::Settings::iconTheme read write
Definition at line 21 of file Settings.hpp.
Referenced by mo::ui::MainWindow::applyIconTheme(), iconThemeChanged(), and setIconTheme().
recentFiles
QStringList mo::core::Settings::recentFiles read write
Definition at line 25 of file Settings.hpp.
Referenced by mo::ui::MainWindow::MainWindow().
showLineNumbers
bool mo::core::Settings::showLineNumbers read write
Definition at line 23 of file Settings.hpp.
tabWidth
int mo::core::Settings::tabWidth read write
Definition at line 22 of file Settings.hpp.
Referenced by mo::ui::CodeEditor::keyPressEvent().
theme
QString mo::core::Settings::theme read write
Definition at line 20 of file Settings.hpp.
Referenced by mo::ui::MainWindow::applyTheme(), setTheme(), and themeChanged().
The documentation for this class was generated from the following files:
src/core/include/mo/core/Settings.hpp
src/core/src/Settings.cpp