Mo: mo::ui::CodeEditor Class Reference
mo::ui::CodeEditor Class Reference
#include <CodeEditor.hpp>
Signals
void modificationChanged (bool modified)
void titleChanged (const QString &title)
Public Member Functions
CodeEditor (QWidget *parent=nullptr)
~CodeEditor () override
QString filePath () const
QString tabTitle () const
bool loadFile (const QString &path)
bool save ()
bool saveAs (const QString &path)
void setLanguage (const QString &extension)
void findNext (const QString &text)
void findPrev (const QString &text)
void applyHighlightingTheme ()
void applyEditorSettings ()
void setShowLineNumbers (bool show)
void zoomFont (int delta)
int lineNumberAreaWidth ()
Protected Member Functions
void resizeEvent (QResizeEvent *event) override
void keyPressEvent (QKeyEvent *event) override
Private Slots
void updateLineNumberAreaWidth (int newBlockCount)
void highlightCurrentLine ()
void updateLineNumberArea (const QRect &rect, int dy)
void onModificationChanged ()
Private Member Functions
void lineNumberAreaPaintEvent (QPaintEvent *event)
void updateTabTitle ()
Private Attributes
LineNumberArea * lineNumberArea_ = nullptr
QString filePath_
bool showLineNumbers_ = true
KSyntaxHighlighting::SyntaxHighlighter * highlighter_ = nullptr
KSyntaxHighlighting::Theme highlightingTheme_
Static Private Attributes
static KSyntaxHighlighting::Repository * repository_ = nullptr
Friends
class LineNumberArea
Detailed Description
Definition at line 20 of file CodeEditor.hpp.
Constructor & Destructor Documentation
CodeEditor()
mo::ui::CodeEditor::CodeEditor (QWidget * parent = nullptr) explicit
Definition at line 52 of file CodeEditor.cpp.
References applyEditorSettings(), applyHighlightingTheme(), highlightCurrentLine(), highlighter_, LineNumberArea, lineNumberArea_, onModificationChanged(), repository_, updateLineNumberArea(), and updateLineNumberAreaWidth().
~CodeEditor()
mo::ui::CodeEditor::~CodeEditor () override default
Member Function Documentation
applyEditorSettings()
void mo::ui::CodeEditor::applyEditorSettings ()
Definition at line 307 of file CodeEditor.cpp.
References mo::core::Settings::instance(), and setShowLineNumbers().
Referenced by CodeEditor().
applyHighlightingTheme()
void mo::ui::CodeEditor::applyHighlightingTheme ()
Definition at line 291 of file CodeEditor.cpp.
References highlightCurrentLine(), highlighter_, highlightingTheme_, lineNumberArea_, and repository_.
Referenced by CodeEditor().
filePath()
QString mo::ui::CodeEditor::filePath () const
Definition at line 79 of file CodeEditor.cpp.
References filePath_.
findNext()
void mo::ui::CodeEditor::findNext (const QString & text)
Definition at line 343 of file CodeEditor.cpp.
Referenced by mo::ui::FindReplaceDock::findNext(), and mo::ui::FindReplaceDock::replace().
findPrev()
void mo::ui::CodeEditor::findPrev (const QString & text)
Definition at line 358 of file CodeEditor.cpp.
Referenced by mo::ui::FindReplaceDock::findPrev().
highlightCurrentLine
void mo::ui::CodeEditor::highlightCurrentLine () private slot
Definition at line 169 of file CodeEditor.cpp.
References highlightingTheme_.
Referenced by applyHighlightingTheme(), and CodeEditor().
keyPressEvent()
void mo::ui::CodeEditor::keyPressEvent (QKeyEvent * event) override protected
Definition at line 136 of file CodeEditor.cpp.
References mo::core::Settings::instance(), and mo::core::Settings::tabWidth.
lineNumberAreaPaintEvent()
void mo::ui::CodeEditor::lineNumberAreaPaintEvent (QPaintEvent * event) private
Definition at line 191 of file CodeEditor.cpp.
References highlightingTheme_, and lineNumberArea_.
lineNumberAreaWidth()
int mo::ui::CodeEditor::lineNumberAreaWidth ()
Definition at line 95 of file CodeEditor.cpp.
References showLineNumbers_.
Referenced by resizeEvent(), setShowLineNumbers(), and updateLineNumberAreaWidth().
loadFile()
bool mo::ui::CodeEditor::loadFile (const QString & path)
Definition at line 234 of file CodeEditor.cpp.
References filePath_, setLanguage(), updateTabTitle(), and mo::core::Logger::warning().
modificationChanged
void mo::ui::CodeEditor::modificationChanged (bool modified) signal
Referenced by mo::ui::MainWindow::newTab(), onModificationChanged(), and mo::ui::MainWindow::openFile().
onModificationChanged
void mo::ui::CodeEditor::onModificationChanged () private slot
Definition at line 373 of file CodeEditor.cpp.
References modificationChanged(), and updateTabTitle().
Referenced by CodeEditor().
resizeEvent()
void mo::ui::CodeEditor::resizeEvent (QResizeEvent * event) override protected
Definition at line 128 of file CodeEditor.cpp.
References lineNumberArea_, and lineNumberAreaWidth().
save()
bool mo::ui::CodeEditor::save ()
Definition at line 253 of file CodeEditor.cpp.
References filePath_, and saveAs().
saveAs()
bool mo::ui::CodeEditor::saveAs (const QString & path)
Definition at line 261 of file CodeEditor.cpp.
References filePath_, and updateTabTitle().
Referenced by save().
setLanguage()
void mo::ui::CodeEditor::setLanguage (const QString & extension)
Definition at line 280 of file CodeEditor.cpp.
References highlighter_, and repository_.
Referenced by loadFile().
setShowLineNumbers()
void mo::ui::CodeEditor::setShowLineNumbers (bool show)
Definition at line 318 of file CodeEditor.cpp.
References lineNumberArea_, lineNumberAreaWidth(), showLineNumbers_, and updateLineNumberAreaWidth().
Referenced by applyEditorSettings().
tabTitle()
QString mo::ui::CodeEditor::tabTitle () const
Definition at line 81 of file CodeEditor.cpp.
References filePath_.
Referenced by updateTabTitle().
titleChanged
void mo::ui::CodeEditor::titleChanged (const QString & title) signal
Referenced by mo::ui::MainWindow::newTab(), mo::ui::MainWindow::openFile(), and updateTabTitle().
updateLineNumberArea
void mo::ui::CodeEditor::updateLineNumberArea (const QRect & rect, int dy) private slot
Definition at line 116 of file CodeEditor.cpp.
References lineNumberArea_, and updateLineNumberAreaWidth().
Referenced by CodeEditor().
updateLineNumberAreaWidth
void mo::ui::CodeEditor::updateLineNumberAreaWidth (int newBlockCount) private slot
Definition at line 110 of file CodeEditor.cpp.
References lineNumberAreaWidth().
Referenced by CodeEditor(), setShowLineNumbers(), and updateLineNumberArea().
updateTabTitle()
void mo::ui::CodeEditor::updateTabTitle () private
Definition at line 379 of file CodeEditor.cpp.
References tabTitle(), and titleChanged().
Referenced by loadFile(), onModificationChanged(), and saveAs().
zoomFont()
void mo::ui::CodeEditor::zoomFont (int delta)
Definition at line 332 of file CodeEditor.cpp.
Friends And Related Symbol Documentation
LineNumberArea
friend class LineNumberArea friend
Definition at line 67 of file CodeEditor.hpp.
References LineNumberArea.
Referenced by CodeEditor(), and LineNumberArea.
Member Data Documentation
filePath_
QString mo::ui::CodeEditor::filePath_ private
Definition at line 72 of file CodeEditor.hpp.
Referenced by filePath(), loadFile(), save(), saveAs(), and tabTitle().
highlighter_
KSyntaxHighlighting::SyntaxHighlighter* mo::ui::CodeEditor::highlighter_ = nullptr private
Definition at line 74 of file CodeEditor.hpp.
Referenced by applyHighlightingTheme(), CodeEditor(), and setLanguage().
highlightingTheme_
KSyntaxHighlighting::Theme mo::ui::CodeEditor::highlightingTheme_ private
Definition at line 75 of file CodeEditor.hpp.
Referenced by applyHighlightingTheme(), highlightCurrentLine(), and lineNumberAreaPaintEvent().
lineNumberArea_
LineNumberArea* mo::ui::CodeEditor::lineNumberArea_ = nullptr private
Definition at line 71 of file CodeEditor.hpp.
Referenced by applyHighlightingTheme(), CodeEditor(), lineNumberAreaPaintEvent(), resizeEvent(), setShowLineNumbers(), and updateLineNumberArea().
repository_
KSyntaxHighlighting::Repository * mo::ui::CodeEditor::repository_ = nullptr static private
Definition at line 76 of file CodeEditor.hpp.
Referenced by applyHighlightingTheme(), CodeEditor(), and setLanguage().
showLineNumbers_
bool mo::ui::CodeEditor::showLineNumbers_ = true private
Definition at line 73 of file CodeEditor.hpp.
Referenced by lineNumberAreaWidth(), and setShowLineNumbers().
The documentation for this class was generated from the following files:
src/ui/editor/CodeEditor.hpp
src/ui/editor/CodeEditor.cpp