Mo: mo::core::Logger Class Reference
mo::core::Logger Class Reference
#include <Logger.hpp>
Static Public Member Functions
static void init ()
static void debug (const QString &message)
static void info (const QString &message)
static void warning (const QString &message)
static void critical (const QString &message)
static void error (const QString &message)
Detailed Description
Definition at line 10 of file Logger.hpp.
Member Function Documentation
critical()
void mo::core::Logger::critical (const QString & message) static
Definition at line 38 of file Logger.cpp.
References critical().
Referenced by critical().
debug()
void mo::core::Logger::debug (const QString & message) static
Definition at line 23 of file Logger.cpp.
References debug().
Referenced by debug().
error()
void mo::core::Logger::error (const QString & message) static
Definition at line 43 of file Logger.cpp.
References error().
Referenced by error().
info()
void mo::core::Logger::info (const QString & message) static
Definition at line 28 of file Logger.cpp.
References info().
Referenced by info(), mo::ui::MainWindow::onFileChanged(), and mo::app::SingleInstance::tryLock().
init()
void mo::core::Logger::init () static
Definition at line 12 of file Logger.cpp.
References init().
Referenced by init(), and mo::app::Application::initLogging().
warning()
void mo::core::Logger::warning (const QString & message) static
Definition at line 33 of file Logger.cpp.
References warning().
Referenced by mo::app::Application::Application(), mo::ui::CodeEditor::loadFile(), mo::app::Application::loadTranslation(), mo::services::FileService::readTextFile(), mo::app::SingleInstance::tryLock(), warning(), and mo::services::FileService::writeTextFile().
The documentation for this class was generated from the following files:
src/core/include/mo/core/Logger.hpp
src/core/src/Logger.cpp