Mo: mo::ui::SettingsDialog Class Reference
mo::ui::SettingsDialog Class Reference
#include <SettingsDialog.hpp>
Signals
void settingsChanged ()
Public Member Functions
SettingsDialog (QWidget *parent=nullptr)
Private Slots
void onAccept ()
Private Member Functions
void load ()
void save ()
Private Attributes
QFontComboBox * fontCombo_ = nullptr
QSpinBox * fontSizeSpin_ = nullptr
QComboBox * themeCombo_ = nullptr
QComboBox * iconThemeCombo_ = nullptr
QSpinBox * tabWidthSpin_ = nullptr
QCheckBox * lineNumbersCheck_ = nullptr
QCheckBox * autoIndentCheck_ = nullptr
Detailed Description
Definition at line 15 of file SettingsDialog.hpp.
Constructor & Destructor Documentation
SettingsDialog()
mo::ui::SettingsDialog::SettingsDialog (QWidget * parent = nullptr) explicit
Definition at line 24 of file SettingsDialog.cpp.
References autoIndentCheck_, fontCombo_, fontSizeSpin_, iconThemeCombo_, lineNumbersCheck_, load(), onAccept(), tabWidthSpin_, and themeCombo_.
Member Function Documentation
load()
void mo::ui::SettingsDialog::load () private
Definition at line 90 of file SettingsDialog.cpp.
References autoIndentCheck_, fontCombo_, fontSizeSpin_, iconThemeCombo_, mo::core::Settings::instance(), lineNumbersCheck_, tabWidthSpin_, and themeCombo_.
Referenced by SettingsDialog().
onAccept
void mo::ui::SettingsDialog::onAccept () private slot
Definition at line 138 of file SettingsDialog.cpp.
References save(), and settingsChanged().
Referenced by SettingsDialog().
save()
void mo::ui::SettingsDialog::save () private
Definition at line 125 of file SettingsDialog.cpp.
References autoIndentCheck_, fontCombo_, fontSizeSpin_, iconThemeCombo_, mo::core::Settings::instance(), lineNumbersCheck_, tabWidthSpin_, and themeCombo_.
Referenced by onAccept().
settingsChanged
void mo::ui::SettingsDialog::settingsChanged () signal
Referenced by mo::ui::MainWindow::editPreferences(), and onAccept().
Member Data Documentation
autoIndentCheck_
QCheckBox* mo::ui::SettingsDialog::autoIndentCheck_ = nullptr private
Definition at line 38 of file SettingsDialog.hpp.
Referenced by load(), save(), and SettingsDialog().
fontCombo_
QFontComboBox* mo::ui::SettingsDialog::fontCombo_ = nullptr private
Definition at line 32 of file SettingsDialog.hpp.
Referenced by load(), save(), and SettingsDialog().
fontSizeSpin_
QSpinBox* mo::ui::SettingsDialog::fontSizeSpin_ = nullptr private
Definition at line 33 of file SettingsDialog.hpp.
Referenced by load(), save(), and SettingsDialog().
iconThemeCombo_
QComboBox* mo::ui::SettingsDialog::iconThemeCombo_ = nullptr private
Definition at line 35 of file SettingsDialog.hpp.
Referenced by load(), save(), and SettingsDialog().
lineNumbersCheck_
QCheckBox* mo::ui::SettingsDialog::lineNumbersCheck_ = nullptr private
Definition at line 37 of file SettingsDialog.hpp.
Referenced by load(), save(), and SettingsDialog().
tabWidthSpin_
QSpinBox* mo::ui::SettingsDialog::tabWidthSpin_ = nullptr private
Definition at line 36 of file SettingsDialog.hpp.
Referenced by load(), save(), and SettingsDialog().
themeCombo_
QComboBox* mo::ui::SettingsDialog::themeCombo_ = nullptr private
Definition at line 34 of file SettingsDialog.hpp.
Referenced by load(), save(), and SettingsDialog().
The documentation for this class was generated from the following files:
src/ui/dialogs/SettingsDialog.hpp
src/ui/dialogs/SettingsDialog.cpp