Mo: mo::ui::FindReplaceDock Class Reference
mo::ui::FindReplaceDock Class Reference
#include <FindReplaceDock.hpp>
Signals
void searchRequested (const QString &text, bool caseSensitive, bool wholeWords, bool regex)
Public Member Functions
FindReplaceDock (QWidget *parent=nullptr)
QString searchText () const
QString replaceText () const
void focusSearch ()
void findNext (CodeEditor *editor)
void findPrev (CodeEditor *editor)
void replace (CodeEditor *editor)
void replaceAll (CodeEditor *editor)
Private Member Functions
void updateStatus (const QString &message)
CodeEditor * currentEditor () const
Private Attributes
QLineEdit * searchEdit_ = nullptr
QLineEdit * replaceEdit_ = nullptr
QCheckBox * caseSensitiveCheck_ = nullptr
QCheckBox * wholeWordsCheck_ = nullptr
QCheckBox * regexCheck_ = nullptr
QPushButton * findNextBtn_ = nullptr
QPushButton * findPrevBtn_ = nullptr
QPushButton * replaceBtn_ = nullptr
QPushButton * replaceAllBtn_ = nullptr
QLabel * statusLabel_ = nullptr
Detailed Description
Definition at line 18 of file FindReplaceDock.hpp.
Constructor & Destructor Documentation
FindReplaceDock()
mo::ui::FindReplaceDock::FindReplaceDock (QWidget * parent = nullptr) explicit
Definition at line 19 of file FindReplaceDock.cpp.
References caseSensitiveCheck_, currentEditor(), findNext(), findNextBtn_, findPrev(), findPrevBtn_, regexCheck_, replace(), replaceAll(), replaceAllBtn_, replaceBtn_, replaceEdit_, searchEdit_, statusLabel_, updateStatus(), and wholeWordsCheck_.
Member Function Documentation
currentEditor()
CodeEditor * mo::ui::FindReplaceDock::currentEditor () const private
Definition at line 97 of file FindReplaceDock.cpp.
Referenced by FindReplaceDock().
findNext()
void mo::ui::FindReplaceDock::findNext (CodeEditor * editor)
Definition at line 125 of file FindReplaceDock.cpp.
References mo::ui::CodeEditor::findNext(), searchText(), and updateStatus().
Referenced by FindReplaceDock().
findPrev()
void mo::ui::FindReplaceDock::findPrev (CodeEditor * editor)
Definition at line 134 of file FindReplaceDock.cpp.
References mo::ui::CodeEditor::findPrev(), searchText(), and updateStatus().
Referenced by FindReplaceDock().
focusSearch()
void mo::ui::FindReplaceDock::focusSearch ()
Definition at line 114 of file FindReplaceDock.cpp.
References searchEdit_.
replace()
void mo::ui::FindReplaceDock::replace (CodeEditor * editor)
Definition at line 143 of file FindReplaceDock.cpp.
References mo::ui::CodeEditor::findNext(), replaceText(), searchText(), and updateStatus().
Referenced by FindReplaceDock().
replaceAll()
void mo::ui::FindReplaceDock::replaceAll (CodeEditor * editor)
Definition at line 157 of file FindReplaceDock.cpp.
References replaceText(), searchText(), and updateStatus().
Referenced by FindReplaceDock().
replaceText()
QString mo::ui::FindReplaceDock::replaceText () const
Definition at line 112 of file FindReplaceDock.cpp.
References replaceEdit_.
Referenced by replace(), and replaceAll().
searchRequested
void mo::ui::FindReplaceDock::searchRequested (const QString & text, bool caseSensitive, bool wholeWords, bool regex) signal
searchText()
QString mo::ui::FindReplaceDock::searchText () const
Definition at line 111 of file FindReplaceDock.cpp.
References searchEdit_.
Referenced by findNext(), findPrev(), replace(), and replaceAll().
updateStatus()
void mo::ui::FindReplaceDock::updateStatus (const QString & message) private
Definition at line 120 of file FindReplaceDock.cpp.
References statusLabel_.
Referenced by findNext(), findPrev(), FindReplaceDock(), replace(), and replaceAll().
Member Data Documentation
caseSensitiveCheck_
QCheckBox* mo::ui::FindReplaceDock::caseSensitiveCheck_ = nullptr private
Definition at line 44 of file FindReplaceDock.hpp.
Referenced by FindReplaceDock().
findNextBtn_
QPushButton* mo::ui::FindReplaceDock::findNextBtn_ = nullptr private
Definition at line 47 of file FindReplaceDock.hpp.
Referenced by FindReplaceDock().
findPrevBtn_
QPushButton* mo::ui::FindReplaceDock::findPrevBtn_ = nullptr private
Definition at line 48 of file FindReplaceDock.hpp.
Referenced by FindReplaceDock().
regexCheck_
QCheckBox* mo::ui::FindReplaceDock::regexCheck_ = nullptr private
Definition at line 46 of file FindReplaceDock.hpp.
Referenced by FindReplaceDock().
replaceAllBtn_
QPushButton* mo::ui::FindReplaceDock::replaceAllBtn_ = nullptr private
Definition at line 50 of file FindReplaceDock.hpp.
Referenced by FindReplaceDock().
replaceBtn_
QPushButton* mo::ui::FindReplaceDock::replaceBtn_ = nullptr private
Definition at line 49 of file FindReplaceDock.hpp.
Referenced by FindReplaceDock().
replaceEdit_
QLineEdit* mo::ui::FindReplaceDock::replaceEdit_ = nullptr private
Definition at line 43 of file FindReplaceDock.hpp.
Referenced by FindReplaceDock(), and replaceText().
searchEdit_
QLineEdit* mo::ui::FindReplaceDock::searchEdit_ = nullptr private
Definition at line 42 of file FindReplaceDock.hpp.
Referenced by FindReplaceDock(), focusSearch(), and searchText().
statusLabel_
QLabel* mo::ui::FindReplaceDock::statusLabel_ = nullptr private
Definition at line 51 of file FindReplaceDock.hpp.
Referenced by FindReplaceDock(), and updateStatus().
wholeWordsCheck_
QCheckBox* mo::ui::FindReplaceDock::wholeWordsCheck_ = nullptr private
Definition at line 45 of file FindReplaceDock.hpp.
Referenced by FindReplaceDock().
The documentation for this class was generated from the following files:
src/ui/dialogs/FindReplaceDock.hpp
src/ui/dialogs/FindReplaceDock.cpp